source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!
target 'IPaImageURLLoader_Tests' do
  pod 'IPaImageURLLoader', :path => '../'
  
  
end
